name: Build oxc daily jar

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  daily:
    if: github.repository == 'oxc/kolmafia'
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/kolmafia/kolmafia
          git fetch upstream

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        env:
          ORG_GRADLE_PROJECT_commit: ${{ github.sha }}
        run: ./gradlew --no-daemon shadowJar

      - name: Get revision
        id: revision
        run: |
          REVISION=$(git rev-list --count upstream/main)
          PATCH_LEVEL=$(git rev-list --count upstream/main..)
          echo "::set-output name=revision::$REVISION"
          echo "::set-output name=filename::KoLmafia-$REVISION-oxc-$PATCH_LEVEL.jar"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "KoLmafia ${{ steps.revision.outputs.revision }}"
          files: |
            dist/${{ steps.revision.outputs.filename }}
