name: Build oxc

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  bin:
    if: github.repository == 'oxc/kolmafia'
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/kolmafia/kolmafia
          git fetch upstream

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        env:
          ORG_GRADLE_PROJECT_commit: ${{ github.sha }}
        run: ./gradlew --no-daemon jpackage

      - name: Zip binaries
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: '${{runner.os}}.zip'
          directory: 'build/releases/'

      - name: Upload zipballs
        uses: actions/upload-artifact@v2
        with:
          name: releases
          path: build/releases/*.zip

  jar:
    if: github.repository == 'oxc/kolmafia'
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/kolmafia/kolmafia
          git fetch upstream

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        env:
          ORG_GRADLE_PROJECT_commit: ${{ github.sha }}
        run: ./gradlew --no-daemon shadowJar

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.jar

  release:
    needs: [bin, jar]
    if: github.repository == 'oxc/kolmafia'
    name: Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/kolmafia/kolmafia
          git fetch upstream

      - name: Retrieve version and tag
        run: |
          REVISION=$(git rev-list --count upstream/main)
          PATCH_LEVEL=$(git rev-list --count upstream/main..)
          KOLMAFIA_VERSION=$REVISION-oxc-$PATCH_LEVEL
          git tag "r$KOLMAFIA_VERSION"
          echo "KOLMAFIA_VERSION=$KOLMAFIA_VERSION" >> $GITHUB_ENV

      - name: Download binaries
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.jar
            releases/*.zip
          tag_name: r${{ env.KOLMAFIA_VERSION }}
          name: ${{ env.KOLMAFIA_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
